#ifndef TRAFFIC_LIGHT_BUTTON_CONFIG_H
#define TRAFFIC_LIGHT_BUTTON_CONFIG_H

#define BUTTON_PIN 1
#define BUTTON_POLLING_INTERVAL_MS 10UL
#define BUTTON_DEBOUNCE_TIME_MS 50UL

#endif  // TRAFFIC_LIGHT_BUTTON_CONFIG_H
