#ifndef TRAFFIC_LIGHT_LIGHT_DURATION_CONFIG_H
#define TRAFFIC_LIGHT_LIGHT_DURATION_CONFIG_H

#define RED_LIGHT_DURATION_MS 5000UL
#define GREEN_LIGHT_DURATION_MS 5000UL
#define GREEN_BLINK_DURATION_MS 3000UL
#define GREEN_BLINK_INTERVAL_MS 500UL
#define YELLOW_BLINK_INTERVAL_MS 500UL
#define YELLOW_LIGHT_DURATION_MS 3000UL
#define RED_AND_YELLOW_DURATION_MS 2000UL

#endif  // TRAFFIC_LIGHT_LIGHT_DURATION_CONFIG_H
