#ifndef TRAFFIC_LIGHT_TIMER_CONFIG_H
#define TRAFFIC_LIGHT_TIMER_CONFIG_H

#define TIMER_NUMBER 0
#define TIMER_PRESCALER 80
#define TIMER_ALARM_PERIOD_US 1000UL

#endif  // TRAFFIC_LIGHT_TIMER_CONFIG_H
